# Generated by Django 3.2 on 2021-08-22 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runo', '0030_messageallusers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutschool',
            options={'ordering': ['-published'], 'verbose_name_plural': 'AboutSchool'},
        ),
        migrations.AlterModelOptions(
            name='academics',
            options={'ordering': ['-published'], 'verbose_name_plural': 'Academics'},
        ),
        migrations.AlterModelOptions(
            name='footerdetails',
            options={'verbose_name_plural': 'Footer Details'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Gallery'},
        ),
        migrations.AlterModelOptions(
            name='importantdates',
            options={'verbose_name_plural': 'Important Dates'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published'], 'verbose_name_plural': 'News'},
        ),
    ]
